config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("dogs.urls", namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from .apps import DogsConfig
from . import views

app_name = DogsConfig.name

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path('<int:pk>/dogs', views.DogListView.as_view(), name='category_dogs'),
    path('dogs/create/', views.DogCreateView.as_view(), name='dog_create'),
    path('dogs/upadte/<int:pk>/', views.DogUpdateView.as_view(), name='dog_update'),
    path('dogs/delete/<int:pk>/', views.DogDeleteView.as_view(), name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

dogs/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'


class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='Кличка')
    # category = models.CharField(max_length=100, verbose_name='Порода')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Порода')

    phot = models.ImageField(upload_to='dogs/', null=True, blank=True, verbose_name='Фото')
    birth_day = models.DateField(null=True, blank=True, verbose_name='Дата рождения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='владелец')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'


class Parent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, verbose_name='Кличка')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Порода')
    birth_day = models.DateField(null=True, blank=True, verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'предок'
        verbose_name_plural = 'предки'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='номер телефона', null=True, blank=True)
    telegram = models.CharField(max_length=150, verbose_name='Telegram username', null=True, blank=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

dogs/forms.py
from django import forms
from .models import Dog, Parent


class DogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = '__all__'


class ParentForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = '__all__'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from dogs.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'telegram', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

dogs/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Category, Dog
from django.urls import reverse_lazy, reverse
from .forms import DogForm, ParentForm


class IndexView(TemplateView):
    template_name = 'dogs/index.html'
    extra_context = {
        'title': 'Питомник - Добро пожаловать',
    }

    def get_context_data(self, **kwargs: Any):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Питомник - Наши породы'
    }


class DogListView(ListView):
    model = Dog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['object_list'] = Dog.objects.filter(category_id=category_item.pk)
        context_data['title'] = f'Все собаки породы {category_item.name}'

        return context_data


class DogCreateView(CreateView):
    model = Dog
    form_class = DogForm
    success_url = reverse_lazy('dogs:categories')


class DogUpdateView(UpdateView):
    model = Dog
    fields = ('name', 'category')

    def get_success_url(self):
        return reverse('dogs:category_dogs', args=[self.object.category.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        if self.request.method == 'POST':
            formset = ParentForm(self.request.POST)
        else:
            formset = ParentForm(initial={"dog": self.object.pk, "category": self.object.category.id})

        context_data['parent_form'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        parent_form = context_data['parent_form']
        self.object = form.save()
        if parent_form.is_valid():
            parent_form.product = self.object
            parent_form.save()

        return super().form_valid(form)


class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('dogs:categories')

users/views.py
import random
from django.shortcuts import render
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from .models import User
from .forms import UserRegisterForm, UserForm
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import redirect
from users.services import send_new_password


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        # send_mail(
        #     subject='Поздравляем в регистрацией',
        #     message='Вы зарегистрировались на нашей платформе, добро пожаловать!',
        #     from_email=settings.EMAIL_HOST_USER,
        #     recipient_list=[new_user.email]
        # )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    request.user.set_password(new_password)
    request.user.save()
    print(new_password)
    # send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <script src="{% static 'js/color-modes.js'%}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Питомник</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">



    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }
    </style>


</head>

<body>
    <header data-bs-theme="dark">
        <div class="collapse text-bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">

                    <div class="col-sm-4 offset-md-1 py-4">
                        <ul class="list-unstyled">
                            <li><a href="{% url 'dogs:index' %}">Главная</a></li>
                            <li><a href="{% url 'dogs:categories' %}">Породы</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'users:logout' %}">Выход</a></li>
                            <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                            {% else %}
                            <li><a href="{% url 'users:login' %}" {# class="text-white" #}>Вход</a></li>
                            <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                        viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                    </svg>
                    <strong>Album</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>


    <main>

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">{{ title }}</h1>
            </div>
        </section>

        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                {% block content %}

                {% endblock %}
            </div>
        </div>

    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

dogs/templates/dogs/category_list.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'dogs:dog_create'%}">Добавить собаку</a>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    {% include 'dogs/includes/inc-category.html' %}

    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dog_confirm_delete.html
{% extends 'dogs/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление собаки
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Дейстивтельно хотите удалить собаку {{ object.name }}</p>
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a class="btn btn-outline-warning" href="{% url 'dogs:category_dogs' object.category.pk %}">Отмена</a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

dogs/templates/dogs/dog_form.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                    Редактирование собаки
                    {% else %}
                    Добавление собаки
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>

                </div>

            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Родитель
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ parent_form.as_p }}

                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/dog_list.html
{% extends 'dogs/base.html' %}
{% block content %}
{% for object in object_list %}
{% load my_tags %}

<div class="col-4">
    <div class="card shadow-sm mb-5">
        <img class="card-img-top" src="{{ object.phot|my_media_filter }}" alt="Card image cap">
        <div class="card-body">
            <p class="card-text">{{object.name|title}}</p>
            <p class="card-text">{{object.description}}</p>
            <p class="card-text">{{object.owner|default:"Без хозяина"}}</p>
            <div class="card-footer">
                <a class="btn btn-link" href="{% url 'dogs:dog_update' object.pk %}">изменить</a>
                <a class="btn btn-outline-danger float-right" href="{% url 'dogs:dog_delete' object.pk %}">удалить</a>
            </div>

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

dogs/templates/dogs/includes/inc-category.html
<div class="col-4">
    <div class="card shadow-sm mb-5">

        <div class="card-body">
            <p class="card-text">{{object.name}}</p>
            <p class="card-text">{{object.description}}</p>
            <div class="btn-group">
                <a href="{% url 'dogs:category_dogs' object.pk %}" type="button"
                    class="btn btn-sm btn-outline-secondary">К собакам</a>
            </div>
            <p class="card-text">
                {% if object.dog_set.exists %}
                всего собак попроды {{object.name}}: {{object.dog_set.all|length}}</p>
                {% else %}
                Пока нет собак такой породы.
                {% endif %}
        </div>
    </div>
</div>

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    {% include 'dogs/includes/inc-category.html' %}
    {% endfor %}
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'dogs/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'dogs/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{form.errors}}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'dogs/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}